"""LaTeX tables of the main study for the paper (paper/tables/), generated from the analysis outputs.

    python scripts/paper_tables.py --analysis results/main_analysis.json \\
        --rerun results/main_analysis_rerun2048.json --wordings results/n1p3_wording_analysis.json \\
        --out paper/tables

Inputs: scripts/main_analysis.py (confirmatory), the same on main.jsonl + main_rerun2048.jsonl (sensitivity),
scripts/wording_analysis.py on main + main_wordings + main_n1p3 (robustness and the exploratory N1P3).
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

MODELS = [("qwen2.5-7b-instruct-bf16", "Qwen2.5-7B"), ("llama3.1-8b-instruct-bf16", "Llama-3.1-8B"),
          ("olmo3-7b-instruct-bf16", "OLMo-3-7B")]
CONDS = ["B1", "G1", "G2", "G3", "G4", "R1", "N1R", "N1P2"]
HEADER = "%% Generated by scripts/paper_tables.py from {src}. Do not edit by hand.\n"


def f3(x: float) -> str:
    return f"{x:.3f}".lstrip("0") if x >= 0 else f"$-${abs(x):.3f}".replace("0.", ".")


def pts(x: float, sign: bool = True) -> str:
    v = 100 * x
    s = f"{abs(v):.1f}"
    return ("+" if v >= 0 else "$-$") + s if sign else s


def ci(lo: float, hi: float) -> str:
    return f"[{pts(lo)}, {pts(hi)}]"


def stars(p: float) -> str:
    return "$^{***}$" if p < .001 else "$^{**}$" if p < .01 else "$^{*}$" if p < .05 else ""


def accuracy_table(res: dict) -> str:
    rows = []
    for key, name in MODELS:
        acc = res["models"][key]["accuracy"]
        best = max(acc[c]["acc"] for c in CONDS if not c.startswith("N"))
        bestn = max(acc[c]["acc"] for c in CONDS)
        cells = []
        for c in CONDS:
            a, b = acc[c]["acc"], acc[c]["balanced"]
            txt = f"{f3(a)}/{f3(b)}"
            if a == bestn or (a == best and not c.startswith("N")):
                txt = r"\textbf{" + txt + "}"
            cells.append(txt)
        rows.append(f"{name:<13} & " + " & ".join(cells) + r"\\")
    n = res["n_items"]
    cov = ", ".join(f"{name.split('-')[0]} {res['models'][k]['accuracy']['N1P2']['coverage']:.3f}" for k, name in MODELS)
    return (HEADER.format(src="results/main_analysis.json") + r"""\begin{table}[t]
\caption{Main study, deep contrast subset (test splits, """ + f"{n:,}".replace(",", r"\,") + r""" items per cell):
accuracy / balanced accuracy. Bold: best prompting condition and best overall per model. Reasoner coverage of
\cond{N1P2}: """ + cov + r""".}
\label{tab:main-accuracy}
\small
\setlength{\tabcolsep}{3.5pt}
\resizebox{\linewidth}{!}{%
\begin{tabular}{l""" + "c" * len(CONDS) + r"""}
\toprule
Model & """ + " & ".join(rf"\cond{{{c}}}" for c in CONDS) + r"""\\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}}
\end{table}
""")


def contrasts_table(res: dict, rerun: dict | None) -> str:
    spec = [("H1 G2>B1", r"H1 & \cond{G2} $-$ \cond{B1}"),
            ("H1u G2>B1 unseen", r"H1u & \cond{G2} $-$ \cond{B1}, unseen"),
            ("H2 G2>G1", r"H2 & \cond{G2} $-$ \cond{G1}"),
            ("H2 G2>G3", r"H2 & \cond{G2} $-$ \cond{G3}"),
            ("H2 G2>G4", r"H2 & \cond{G2} $-$ \cond{G4}"),
            ("H2 G2>R1", r"H2 & \cond{G2} $-$ \cond{R1}"),
            ("H2-null G4~G1 (TOST)", r"H2 & \cond{G4} $-$ \cond{G1}$^{\dagger}$"),
            ("H3 N1P2 vs G2", r"H3 & \cond{N1P2} $-$ \cond{G2}")]
    rows = []
    for k, label in spec:
        cells = []
        for key, _ in MODELS:
            t = res["models"][key]["tests"][k]
            if "p_tost" in t:
                cells.append(f"{pts(t['diff'])} {ci(*t['ci90'])}")
            else:
                p = t.get("p_holm", t.get("p_two_sided", t["p_cluster_t"]))
                cells.append(f"{pts(t['diff'])} {ci(*t['ci95'])}{stars(p)}")
        rows.append(label + " & " + " & ".join(cells) + r"\\")
    note = ""
    if rerun:
        t = rerun["models"]["llama3.1-8b-instruct-bf16"]["tests"]["H2 G2>R1"]
        note = (r" With the 91 Llama answers truncated at 1\,024 tokens regenerated at 2\,048 tokens (exploratory),"
                rf" Llama's \cond{{G2}} $-$ \cond{{R1}} is {pts(t['diff'])} {ci(*t['ci95'])}, $p={t['p_cluster_t']:.3f}$.")
    return (HEADER.format(src="results/main_analysis.json") + r"""\begin{table}[t]
\caption{Preregistered contrasts (accuracy difference in points, 95\,\% cluster-bootstrap CI over EN/ES twin
clusters). H1, H1u and H2 one-sided cluster $t$-tests (H2 Holm-corrected within model); H3 two-sided.
$^{*}p<.05$, $^{**}p<.01$, $^{***}p<.001$. $^{\dagger}$Equivalence test (TOST, margin $\pm$3 points, 90\,\% CI):
equivalence is not shown for any model.""" + note + r"""}
\label{tab:main-contrasts}
\small
\setlength{\tabcolsep}{3pt}
\resizebox{\linewidth}{!}{%
\begin{tabular}{llccc}
\toprule
& Contrast & """ + " & ".join(n for _, n in MODELS) + r"""\\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}}
\end{table}
""")


def diagnostics_table(res: dict) -> str:
    cols = ["evidence_sensitivity", "counterfactual_affected", "counterfactual_control", "exceptions", "novel"]
    rows = []
    for key, name in MODELS:
        d = res["models"][key]["diagnostics"]
        conds = ["B1", "G2", "R1", "N1P2"]
        for k, c in enumerate(conds):
            first = rf"\multirow{{{len(conds)}}}{{*}}{{{name}}}" if k == 0 else ""
            rows.append(f"{first} & \\cond{{{c}}} & " + " & ".join(f3(d[c][x][0]) for x in cols) + r"\\")
        rows.append(r"\addlinespace")
    n = {x: res["models"][MODELS[0][0]]["diagnostics"]["G2"][x][1] for x in cols}
    return (HEADER.format(src="results/main_analysis.json") + r"""\begin{table}[t]
\caption{Reasoning-versus-recall diagnostics (main study). Evidence sensitivity: share of ablation pairs answered
correctly when intact \emph{and} as \emph{undetermined} when a required fact is removed (""" + str(n["evidence_sensitivity"]) +
r""" pairs); accuracy on counterfactual affected (""" + str(n["counterfactual_affected"]) + r""") and control (""" +
str(n["counterfactual_control"]) + r""") items, exception items (""" + str(n["exceptions"]) + r""") and pseudoword
(novel) concepts (""" + str(n["novel"]) + r""").}
\label{tab:main-diagnostics}
\small
\begin{tabular}{llccccc}
\toprule
Model & Cond. & Evidence sens. & CF affected & CF control & Exceptions & Novel\\
\midrule
""" + "\n".join(rows[:-1]) + r"""
\bottomrule
\end{tabular}
\end{table}
""")


def wordings_table(w: dict) -> str:
    conds = ["B1", "G2", "G3", "N1P2", "N1P3"]
    rows = []
    for key, name in MODELS:
        for k, c in enumerate(conds):
            a = w[f"{key}/{c}"]["acc"]
            first = rf"\multirow{{{len(conds)}}}{{*}}{{{name}}}" if k == 0 else ""
            lab = rf"\cond{{{c}}}" + (r"$^{\ddagger}$" if c == "N1P3" else "")
            rows.append(f"{first} & {lab} & {f3(a['w1'])} & {f3(a['w2'])} & {f3(a['w3'])} & "
                        f"{f3(w[f'{key}/{c}']['consistency'])}" + r"\\")
        rows.append(r"\addlinespace")
    pairs = (("G2", "B1"), ("N1P2", "G2"), ("N1P3", "G2"))
    diff_rows = []
    for key, name in MODELS:
        cells = []
        for x, y in pairs:
            t = w[f"{key}/{x}-{y}/w3"]
            cells.append(f"{pts(t['diff'])} {ci(*t['ci'])}")
        diff_rows.append(f"{name} & " + " & ".join(cells) + r"\\")
    n = w[f"{MODELS[0][0]}/G2"]["n"]
    return (HEADER.format(src="results/n1p3_wording_analysis.json") + r"""\begin{table}[t]
\caption{Robustness to wording on the """ + str(n) + r""" base items that have all three wordings: W1 original
template, W2 rule-based rewording, W3 filtered LLM paraphrase. Consistency: same answer in the three wordings.
Differences in points with 95\,\% cluster-bootstrap CIs. $^{\ddagger}$Exploratory, defined after the confirmatory
run (\S\ref{sec:results-n1p3}).}
\label{tab:main-wordings}
\small
\begin{tabular}{llcccc}
\toprule
Model & Cond. & W1 & W2 & W3 & Consistency\\
\midrule
""" + "\n".join(rows[:-1]) + r"""
\bottomrule
\end{tabular}

\medskip
\begin{tabular}{lccc}
\toprule
W3 difference & \cond{G2} $-$ \cond{B1} & \cond{N1P2} $-$ \cond{G2} & \cond{N1P3}$^{\ddagger}$ $-$ \cond{G2}\\
\midrule
""" + "\n".join(diff_rows) + r"""
\bottomrule
\end{tabular}
\end{table}
""")


def ablations_table(ab: dict) -> str:
    """S3 (lexicon-expanded KB) and S4 (G2 components, Qwen)."""
    rows = []
    for key, name in MODELS:
        for c in ("G2", "N1P2"):
            cells = []
            for w in ("w1", "w2", "w3"):
                t = ab["S3"].get(f"{key}/{c}/{w}")
                cells.append("--" if t is None else f"{pts(t['diff'])} {ci(*t['ci'])}")
            rows.append(f"{name} & \\cond{{{c}}} & " + " & ".join(cells) + r"\\")
    s4 = []
    labels = {"+postulates": "no frames, no Cognicon", "-hedges": "no always/typically", "-fillers": "no filler expansion"}
    q = MODELS[0][0]
    for abl, lab in labels.items():
        cells = []
        for blk in ("all", "exceptions", "deep_real", "novel"):
            t = ab["S4"].get(f"{q}/{abl}/{blk}")
            cells.append("--" if t is None else f"{pts(t['diff'])} {ci(*t['ci'])}")
        s4.append(f"{lab} & " + " & ".join(cells) + r"\\")
    return (HEADER.format(src="results/main_ablations.json") + r"""\begin{table}[t]
\caption{Ablations (accuracy difference in points, 95\,\% cluster-bootstrap CI). Top (S3): knowledge base with the
expert-approved lexicon expansion minus the base knowledge base, per wording. Bottom (S4, Qwen2.5-7B): \cond{G2}
with one component removed minus full \cond{G2}, on all items and on the blocks where the component should matter
(""" + str(ab["S4"][f"{q}/-hedges/exceptions"]["n"]) + r""" exception, """ + str(ab["S4"][f"{q}/-hedges/deep_real"]["n"]) +
                r""" real-inheritance and """ + str(ab["S4"][f"{q}/-hedges/novel"]["n"]) + r""" novel-concept items).}
\label{tab:main-ablations}
\small
\setlength{\tabcolsep}{3pt}
\resizebox{\linewidth}{!}{%
\begin{tabular}{llccc}
\toprule
\multicolumn{2}{l}{S3: lexicon expansion} & W1 & W2 & W3\\
\midrule
""" + "\n".join(rows) + r"""
\bottomrule
\end{tabular}}

\medskip
\resizebox{\linewidth}{!}{%
\begin{tabular}{lcccc}
\toprule
S4: \cond{G2} without & All & Exceptions & Real inheritance & Novel\\
\midrule
""" + "\n".join(s4) + r"""
\bottomrule
\end{tabular}}
\end{table}
""")


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--analysis", default="results/main_analysis.json")
    ap.add_argument("--rerun", default="results/main_analysis_rerun2048.json")
    ap.add_argument("--wordings", default="results/n1p3_wording_analysis.json")
    ap.add_argument("--ablations", default="results/main_ablations.json")
    ap.add_argument("--out", default="paper/tables")
    a = ap.parse_args(argv)
    res = json.loads(Path(a.analysis).read_text(encoding="utf-8"))
    rerun = json.loads(Path(a.rerun).read_text(encoding="utf-8")) if Path(a.rerun).exists() else None
    w = json.loads(Path(a.wordings).read_text(encoding="utf-8"))
    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)
    for name, text in (("main_accuracy", accuracy_table(res)), ("main_contrasts", contrasts_table(res, rerun)),
                       ("main_diagnostics", diagnostics_table(res)), ("main_wordings", wordings_table(w))):
        (out / f"{name}.tex").write_text(text, encoding="utf-8")
        print("written", out / f"{name}.tex")
    if Path(a.ablations).exists():
        ab = json.loads(Path(a.ablations).read_text(encoding="utf-8"))
        (out / "main_ablations.tex").write_text(ablations_table(ab), encoding="utf-8")
        print("written", out / "main_ablations.tex")


if __name__ == "__main__":
    main()
