"""Alternative wordings of deep items (prompt robustness, P16).

Every deep item is asked in three wordings; the gold answer, the knowledge base patch and the queried
property do not change, only the surface text:

* **W1** — the original template: "Is it true that <h>? Answer yes, no or undetermined."
* **W2** — rule-based variation: a direct yes/no question by subject--verb inversion ("Does a lone wolf
  deal with a crime?", "¿Comercia un lobo solitario con un delito?"; when inversion is not safe, the frame
  "Is it correct that <h>?" / "¿Es correcto afirmar que <h>?", whose frame words are not KB events) and,
  for nouns whose alternative lemma has been approved by a FunGramKB expert
  (``data/extension/w2_synonyms.json``), another lemma of the same concept ("a crime" -> "an offence").
  The lexicon groups near-synonyms and hyponymic lexicalisations under one concept (amphetamine /
  methamphetamine), so alternatives are used only after approval. Articles are regenerated by the
  verbaliser, Spanish substitutions must keep the gender (the predicate agrees with it) and every
  substitution is checked with the shared linker.
* **W3** — free paraphrase by an LLM that is not one of the evaluated models
  (``scripts/make_wordings.py --paraphrase``), filtered by automatic checks (``check_paraphrase``) and
  audited by a human on a sample.

The proposition always stays inside the question sentence, so the neuro-symbolic pipelines see the
same kind of input in all wordings; the answer instruction is always the original one, so answer
parsing does not depend on the wording.
"""

from __future__ import annotations

import copy
import hashlib
import re

from ..corel import nlg
from ..kb.model import KnowledgeBase
from .schema import Item

INSTRUCTION = {"en": "Answer yes, no or undetermined.", "es": "Responde sí, no o indeterminado."}
W1_FRAME = {"en": "Is it true that ", "es": "¿Es cierto que "}
W2_FRAME = {"en": "Is it correct that ", "es": "¿Es correcto afirmar que "}
NEGATION = {"en": re.compile(r"\b(not|never|no|n't)\b", re.IGNORECASE), "es": re.compile(r"\b(no|nunca|jamás|ningún|ninguna)\b", re.IGNORECASE)}


def split_item_text(question: str, lang: str) -> tuple[str, str] | None:
    """(background sentences, proposition h without final '?') of a W1 question, or None."""
    q = question.strip()
    instr = INSTRUCTION[lang]
    if not q.endswith(instr):
        return None
    q = q[: -len(instr)].strip()
    frame = W1_FRAME[lang]
    i = q.rfind(frame)
    if i < 0 or not q.endswith("?"):
        return None
    return q[:i].strip(), q[i + len(frame):-1].strip()


def join_item_text(background: str, question_sentence: str, lang: str) -> str:
    bg = (background.strip() + " ") if background.strip() else ""
    return f"{bg}{question_sentence.strip()} {INSTRUCTION[lang]}"


# ---------------------------------------------------------------------------------------- W2
def _with_first_lemma(kb: KnowledgeBase, cid: str, lang: str, lemma: str) -> KnowledgeBase:
    """Shallow KB view in which `lemma` is the first lemma of `cid` in `lang` (so the verbaliser's NP
    functions use it, with the right article and gender)."""
    view = copy.copy(kb)
    first = [lu for lu in kb.lexicon if lu.concept == cid and lu.lang == lang and lu.lemma == lemma]
    ids = {id(lu) for lu in first}
    view.lexicon = first + [lu for lu in kb.lexicon if id(lu) not in ids]
    return view


def candidate_alternative(kb: KnowledgeBase, cid: str, lang: str) -> str | None:
    lemmas = kb.lemmas(cid, lang)
    if len(lemmas) < 2:
        return None
    cands = [lem for lem in lemmas[1:] if lemmas[0] not in lem.split() and lem.lower() != lemmas[0].lower()]
    if not cands:
        return None
    # deterministic choice per concept and language
    k = int(hashlib.sha1(f"{cid}|{lang}".encode()).hexdigest(), 16) % len(cands)
    return cands[k]


def _np(kb: KnowledgeBase, cid: str, lang: str) -> str:
    return nlg._en_np(kb, cid) if lang == "en" else nlg._es_np(kb, cid)[0]


def substitute_nouns(kb: KnowledgeBase, linker, text: str, lang: str,
                     approved: dict[str, dict[str, str]] | None = None) -> tuple[str, list[tuple[str, str, str]]]:
    """Replace singular, unquantified NPs of entities by another lemma of the same concept.

    ``approved`` maps concept -> language -> alternative lemma; without it nothing is substituted.
    Returns the new text and the substitutions made (concept, old NP, new NP). A substitution is kept
    only if the linker still finds the concept in the new text (and finds no concept that was not there).
    """
    if not approved:
        return text, []
    before = set(linker.concepts(text, lang))
    subs = []
    for cid in list(dict.fromkeys(linker.concepts(text, lang))):
        con = kb.concepts.get(cid)
        if con is None or con.semantic_type != "entity":
            continue
        alt = (approved.get(cid) or {}).get(lang)
        if not alt or alt not in kb.lemmas(cid, lang):
            continue
        view = _with_first_lemma(kb, cid, lang, alt)
        if lang == "es" and nlg.es_feminine(kb.label(cid, lang)) != nlg.es_feminine(alt):
            continue  # "la marihuana es ingerido": the predicate agrees with the original gender
        old, new = _np(kb, cid, lang), _np(view, cid, lang)
        pat = re.compile(rf"(?<![\w-]){re.escape(old)}(?![\w-])", re.IGNORECASE)
        if old == new or not pat.search(text):
            continue

        def repl(m, new=new):
            return new[:1].upper() + new[1:] if m.group(0)[:1].isupper() else new

        cand = pat.sub(repl, text)
        after = set(linker.concepts(cand, lang))
        if cid in after and after <= before | {cid}:
            text = cand
            subs.append((cid, old, new))
    return text, subs


def _en_base(verb: str) -> str:
    irregular = {s3: base for base, (s3, _) in nlg.EN_IRREG.items() if " " not in base}
    if verb in irregular:
        return irregular[verb]
    if verb.endswith("ies") and len(verb) > 4:
        return verb[:-3] + "y"
    if verb.endswith(("sses", "shes", "ches", "xes", "zes", "oes")):
        return verb[:-2]
    return verb[:-1] if verb.endswith("s") and not verb.endswith("ss") else verb


def _subject_end(item: Item, kb: KnowledgeBase, linker, h: str) -> int | None:
    """End offset of the subject NP at the start of the proposition h (the queried concept)."""
    focus = item.focus_concepts[0] if item.focus_concepts else None
    for m in linker.link(h, item.lang):
        if m.concept == focus and m.start <= 6:
            return m.end
    for w in pseudowords(item, kb):
        m = re.match(rf"^\s*(?:(?:a|an|un|una)\s+)?{re.escape(w)}\b", h, re.IGNORECASE)
        if m:
            return m.end()
    return None


def invert(item: Item, kb: KnowledgeBase, linker, h: str) -> str | None:
    """Direct yes/no question from the declarative proposition h, or None when inversion is not safe."""
    end = _subject_end(item, kb, linker, h)
    if end is None:
        return None
    subj, rest = h[:end].strip(), h[end:].strip().split()
    if not rest:
        return None
    if item.lang == "en":
        v = rest[0].lower()
        if v in ("not", "never", "does", "do", "can", "will") or (len(rest) > 1 and rest[1] in ("not", "never")):
            return None
        if v in ("is", "are"):
            return f"{v.capitalize()} {subj} {' '.join(rest[1:])}?"
        if not v.endswith("s"):
            return None
        return f"Does {subj} {_en_base(v)} {' '.join(rest[1:])}".strip() + "?"
    v = rest[0].lower()
    if v in ("no", "nunca", "jamás"):
        return None
    verb, tail = (" ".join(rest[:2]), rest[2:]) if v == "se" and len(rest) > 1 else (rest[0], rest[1:])
    if v in ("es", "está") and len(tail) == 1:  # copula + adjective: "¿Es pequeña una bomba?"
        return f"¿{verb[:1].upper()}{verb[1:]} {tail[0]} {subj}?"
    return f"¿{verb[:1].upper()}{verb[1:]} {subj} {' '.join(tail)}".strip() + "?"


def w2_item(kb: KnowledgeBase, linker, item: Item, approved: dict | None = None) -> Item | None:
    parts = split_item_text(item.question, item.lang)
    if parts is None:
        return None
    bg, h = parts
    bg2, subs_bg = substitute_nouns(kb, linker, bg, item.lang, approved) if bg else ("", [])
    h2, subs_h = substitute_nouns(kb, linker, h, item.lang, approved)
    q = invert(item, kb, linker, h2)
    form = "inversion" if q else "frame"
    if q is None:
        q = f"{W2_FRAME[item.lang]}{h2}?"
    return derived(item, "w2", join_item_text(bg2, q, item.lang), w2_form=form,
                   substitutions=[list(s) for s in subs_bg + subs_h])


# ---------------------------------------------------------------------------------------- W3
PARAPHRASE_PROMPT = {
    "en": (
        "Rewrite the text below with different words and sentence structure while keeping EXACTLY the same "
        "meaning. Rules: keep every made-up word (such as {pseudo}) exactly as written; keep negations; keep "
        "quantities such as 'many' or 'some'; the last sentence must remain a yes/no question about the same "
        "statement, with the same subject (what the question is about stays the grammatical subject); do not add information, explanations or an answer. Return exactly ONE rewritten version, "
        "with no alternatives, notes or comments.\n\n"
        "Text: {text}"
    ),
    "es": (
        "Reescribe el texto siguiente con otras palabras y otra estructura sintáctica manteniendo EXACTAMENTE "
        "el mismo significado. Reglas: conserva tal cual toda palabra inventada (como {pseudo}); conserva las "
        "negaciones; conserva cuantificadores como 'muchos' o 'algunos'; la última oración debe seguir siendo "
        "una pregunta de sí o no sobre la misma afirmación y con el mismo sujeto (aquello por lo que se pregunta "
        "sigue siendo el sujeto gramatical); no añadas información, explicaciones ni la "
        "respuesta. Devuelve UNA sola versión reescrita, sin alternativas, notas ni comentarios.\n\nTexto: {text}"
    ),
}


def paraphrase_source(item: Item) -> str | None:
    """The text given to the paraphraser: background + question sentence, without the instruction."""
    parts = split_item_text(item.question, item.lang)
    if parts is None:
        return None
    bg, h = parts
    return (bg + " " if bg else "") + f"{W1_FRAME[item.lang]}{h}?"


def pseudowords(item: Item, kb: KnowledgeBase) -> list[str]:
    """Made-up words of the item (concepts of its KB patch that are not in the base KB)."""
    patch = item.meta.get("kb_patch") or {}
    words = []
    for cid, spec in (patch.get("concepts") or {}).items():
        if cid in kb.concepts or not isinstance(spec, dict):
            continue
        lemma = (spec.get("lemmas") or {}).get(item.lang)
        words.append(lemma or cid.strip("$+#").rsplit("_", 1)[0].lower())
    return [w for w in dict.fromkeys(words) if w]


_NOTE = re.compile(r"^\s*(\(|\*|note|nota|alternativ|or:|o:|versi[oó]n|option|opci[oó]n|elige|choose)", re.IGNORECASE)


def clean_paraphrase(text: str) -> str:
    """First version only: instruction-tuned paraphrasers often append alternatives or notes after a blank
    line ("(Note: ...)", "Alternatively: ..."). Labels such as "Text:" / "Texto:" are removed."""
    t = (text or "").strip()
    first = re.split(r"\n\s*\n", t, maxsplit=1)[0]
    lines = [ln for ln in first.splitlines() if ln.strip() and not _NOTE.match(ln)]
    out = " ".join(ln.strip() for ln in lines)
    out = re.sub(r"^(rewritten text|text|texto reescrito|texto)\s*:\s*", "", out, flags=re.IGNORECASE)
    return out.strip().strip('"').strip("«»").strip()


def check_paraphrase(source: str, para: str, item: Item, kb: KnowledgeBase, linker) -> str | None:
    """None if the paraphrase passes the automatic checks, else the reason it is rejected."""
    lang = item.lang
    p = clean_paraphrase(para)
    if not p or len(p) > 3 * len(source) + 40:
        return "empty or too long"
    if not p.endswith("?"):
        return "last sentence is not a question"
    if re.search(r"\b(yes|no|undetermined|sí|indeterminado)\s*[.!]?\s*$", p.rstrip("?"), re.IGNORECASE) and \
            re.search(r"\b(answer|respuesta|responde)\b", p, re.IGNORECASE):
        return "contains an answer"
    for w in pseudowords(item, kb):
        if w.lower() not in p.lower():
            return f"pseudoword '{w}' lost"
    if len(NEGATION[lang].findall(source)) != len(NEGATION[lang].findall(p)):
        return "negation changed"
    n_src = len(re.findall(r"[.?!](\s|$)", source))
    n_par = len(re.findall(r"[.?!](\s|$)", p))
    if n_par != n_src:
        return "number of sentences changed"
    focus = item.focus_concepts[0] if item.focus_concepts else None
    if focus and focus in kb.concepts and focus not in linker.concepts(p, lang):
        return "focus concept not found by the linker"
    # generic -> existential: "A drolnen is a kind of ecstasy" -> "Some drolnens are ..." (human audit, 7 Oct 2026)
    if len(_EXISTENTIAL[lang].findall(p)) > len(_EXISTENTIAL[lang].findall(source)):
        return "generic statement made existential"
    return None


_EXISTENTIAL = {"en": re.compile(r"(?:^|[.?!]\s+)(?:some|certain)\b", re.IGNORECASE),
                "es": re.compile(r"(?:^|[.?!¿]\s*)(?:algun[oa]s|ciert[oa]s)\b", re.IGNORECASE)}


def subject_changed(para: str, item: Item, kb: KnowledgeBase, linker) -> bool:
    """True when the question's grammatical subject is no longer the queried concept ("Is alcohol ingested by
    a human?" -> "Does a person consume alcohol?"). Not a rejection criterion: the human audit judged most
    of these paraphrases equivalent (voice alternation); the flag lets the analysis report them separately,
    since the neuro-symbolic pipelines query the subject's closure."""
    p = clean_paraphrase(para)
    question = re.findall(r"[^.?!]*\?", p)
    q = question[-1] if question else p
    first = _first_entity(q, item, kb, linker)
    focus = item.focus_concepts[0] if item.focus_concepts else None
    return first is not None and first != focus


def _first_entity(text: str, item: Item, kb: KnowledgeBase, linker) -> str | None:
    """The first entity mentioned in a sentence: a pseudoword of the item or a linked entity concept."""
    hits = []
    for w in pseudowords(item, kb):
        m = re.search(rf"\b{re.escape(w)}", text, re.IGNORECASE)
        if m:
            hits.append((m.start(), item.focus_concepts[0] if item.focus_concepts else w))
    for mention in linker.link(text, item.lang):
        con = kb.concepts.get(mention.concept)
        if con is not None and con.semantic_type == "entity":
            hits.append((mention.start, mention.concept))
            break
    return min(hits)[1] if hits else None


def w3_item(item: Item, para: str, **meta) -> Item:
    return derived(item, "w3", join_item_text("", clean_paraphrase(para), item.lang), **meta)


# ---------------------------------------------------------------------------------------- common
def derived(item: Item, wording: str, question: str, **meta) -> Item:
    new = copy.deepcopy(item)
    new.id = f"{item.id}@{wording}"
    new.pair_id = f"{item.pair_id}@{wording}" if item.pair_id else None  # twins stay paired within a wording
    new.question = question
    new.meta = {**item.meta, "wording": wording, "base_id": item.id, **meta}
    return new
